id = "mcp-server-zai-web-reader"
name = "Z.AI Web Reader MCP Server"
description = "Model Context Protocol Server for Z.AI Web Reader"
version = "0.1.0"
schema_version = 1
authors = ["minggliangg"]
repository = "https://github.com/minggliangg/zed-mcp-server-zai-web-reader"

[context_servers.mcp-server-zai-web-reader]
name = "Z.AI Web Reader MCP Server"
